# action.yml
name: 'Caterspot Deployment'
description: 'Caterspot Deployment'
author: 'Faizal Zakaria'
inputs:
  app:
    description: 'Name of the app, ex: caterspot_admin_app'
    required: true
  aws_key:
    description: 'AWS key'
    required: true
  aws_secret:
    description: 'AWS Secret'
    required: true
  aws_account:
    description: 'AWS account'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  github_key:
    description: 'Github key'
    required: true
  environment:
    description: 'App environment'
    required: true
  version:
    description: 'App version'
    required: true
  infra_repo:
    description: 'CaterSpot Infra Repo'

outputs:
  result:
    description: 'Result'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.aws_key }}
    - ${{ inputs.aws_secret }}
    - ${{ inputs.aws_account }}
    - ${{ inputs.aws_region }}
    - ${{ inputs.github_key }}
    - ${{ inputs.environment }}
    - ${{ inputs.version }}
    - ${{ inputs.infra_repo }}
